version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - "> 2.2.7.RELEASE, < 3"
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - ">= 2.4.a, < 2.5"
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.40"
    - "8.41"
    - 8.41.1
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  target-branch: 2.0.x
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - "> 2.0.9.RELEASE, < 3"
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - "< 2.2, >= 2.1.a"
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - ">= 2.2.a, < 2.3"
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.40"
    - "8.41"
    - 8.41.1
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  target-branch: 2.1.x
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - "> 2.1.9.RELEASE, < 3"
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.40"
    - "8.41"
    - 8.41.1
